### ISSUE TITLE
examples/cli/keras.py crashes

### ISSUE THREAD

**Issue by jeremyfowers** [groq/mlagility#116]
Repro:
```
(mla) jfowers@jfowers:~/mlagility/examples/cli$ export MLAGILITY_TRACEBACK=True
(mla) jfowers@jfowers:~/mlagility/examples/cli$ benchit keras.py
```

Result:
```
Models discovered during profiling:

keras.py:
        trackable (executed 1x)
                Model Type:     Keras (tf.keras.Model)
                Class:          SmallKerasModel (<class 'keras.SmallKerasModel'>)
                Location:       /net/home/jfowers/miniconda3/envs/mla/lib/python3.8/site-packages/tensorflow/python/trackable/data_structures.py, line 163
                Parameters:     55 (<0.1 MB)
                Hash:           5a591a29
                Status:         Unknown benchit error: Error: Failure to run model using onnxruntime - 
                Traceback (most recent call last):
                  File "/home/jfowers/mlagility/src/mlagility/analysis/analysis.py", line 111, in call_benchit
                    perf = benchmark_model(
                  File "/home/jfowers/mlagility/src/mlagility/api/model_api.py", line 178, in benchmark_model
                    perf = cpu_model.benchmark(backend=backend)
                  File "/home/jfowers/mlagility/src/mlagility/api/ortmodel.py", line 20, in benchmark
                    benchmark_results = self._execute(repetitions=repetitions, backend=backend)
                  File "/home/jfowers/mlagility/src/mlagility/api/ortmodel.py", line 71, in _execute
                    devices.execute_cpu_locally(self.state, self.device, repetitions)
                  File "/home/jfowers/mlagility/src/mlagility/api/devices.py", line 624, in execute_cpu_locally
                    raise BenchmarkException(
                mlagility.api.devices.BenchmarkException: Error: Failure to run model using onnxruntime - 
keras_outputs: [[0.         0.         0.         0.06743672 0.        ]]

Woohoo! The 'benchmark' command is complete. Use the 'report' command to get a .csv file that summarizes results across all builds in the cache.
```

**Comment by jeremyfowers** [comment]
cc @danielholanda

**Comment by jeremyfowers** [comment]
As part of fixing this bug, also fix how useless the traceback is!
