### ISSUE TITLE
Embedding layer crashes ORT benchmarking

### ISSUE THREAD

**Issue by jeremyfowers** [groq/mlagility#124]
Repro command:

```
benchit models/transformers_pytorch/electra.py --max-depth 1
```

Result:

```
Models discovered during profiling:

electra.py:
        model (executed 1x)
                Model Type:     Pytorch (torch.nn.Module)
                Class:          ElectraModel (<class 'transformers.models.electra.modeling_electra.ElectraModel'>)
                Location:       /home/jfowers/mlagility/models/transformers_pytorch/electra.py, line 15
                Parameters:     13,483,008 (25.7 MB)
                Hash:           8da49ae6
                Status:         Model successfully benchmarked on Intel(R) Xeon(R) CPU @ 2.20GHz
                                Mean Latency:   0.528   milliseconds (ms)
                                Throughput:     189.4   inferences per second (IPS)

electra.py:
                        embeddings (executed 1x)
                                Model Type:     Pytorch (torch.nn.Module)
                                Class:          ElectraEmbeddings (<class 'transformers.models.electra.modeling_electra.ElectraEmbeddings'>)
                                Parameters:     3,972,864 (7.6 MB)
                                Hash:           9eecb1a3
                                Status:         Unknown benchit error: Error: Failure to run model using onnxruntime - Traceback (most recent call last):
  File "/home/jfowers/.cache/mlagility/electra_9eecb1a3/x86_benchmark/execute-cpu.py", line 164, in <module>
    run(
  File "/home/jfowers/.cache/mlagility/electra_9eecb1a3/x86_benchmark/execute-cpu.py", line 94, in run
    perf_result, exception = run_ort_profile(onnx_file, num_iterations)
  File "/home/jfowers/.cache/mlagility/electra_9eecb1a3/x86_benchmark/execute-cpu.py", line 29, in run_ort_profile
    input_feed = _dummy_inputs(sess_input)
  File "/home/jfowers/.cache/mlagility/electra_9eecb1a3/x86_benchmark/execute-cpu.py", line 68, in _dummy_inputs
    input_feed[stat[0]] = np.random.rand(*stat[1]).astype(datatype)
AttributeError: 'float' object has no attribute 'astype'
                                Traceback (most recent call last):
                                  File "/home/jfowers/mlagility/src/mlagility/analysis/analysis.py", line 123, in call_benchit
                                    perf = benchmark_model(
                                  File "/home/jfowers/mlagility/src/mlagility/api/model_api.py", line 178, in benchmark_model
                                    perf = cpu_model.benchmark(backend=backend)
                                  File "/home/jfowers/mlagility/src/mlagility/api/ortmodel.py", line 20, in benchmark
                                    benchmark_results = self._execute(repetitions=repetitions, backend=backend)
                                  File "/home/jfowers/mlagility/src/mlagility/api/ortmodel.py", line 71, in _execute
                                    devices.execute_cpu_locally(self.state, self.device, repetitions)
                                  File "/home/jfowers/mlagility/src/mlagility/api/devices.py", line 624, in execute_cpu_locally
                                    raise BenchmarkException(
                                mlagility.api.devices.BenchmarkException: Error: Failure to run model using onnxruntime - Traceback (most recent call last):
                                  File "/home/jfowers/.cache/mlagility/electra_9eecb1a3/x86_benchmark/execute-cpu.py", line 164, in <module>
                                    run(
                                  File "/home/jfowers/.cache/mlagility/electra_9eecb1a3/x86_benchmark/execute-cpu.py", line 94, in run
                                    perf_result, exception = run_ort_profile(onnx_file, num_iterations)
                                  File "/home/jfowers/.cache/mlagility/electra_9eecb1a3/x86_benchmark/execute-cpu.py", line 29, in run_ort_profile
                                    input_feed = _dummy_inputs(sess_input)
                                  File "/home/jfowers/.cache/mlagility/electra_9eecb1a3/x86_benchmark/execute-cpu.py", line 68, in _dummy_inputs
                                    input_feed[stat[0]] = np.random.rand(*stat[1]).astype(datatype)
                                AttributeError: 'float' object has no attribute 'astype'
```

**Comment by jeremyfowers** [comment]
fyi @danielholanda
