### ISSUE TITLE
benchmark_script() must continue after one input script fails

### ISSUE THREAD

**Issue by danielholanda** [groq/mlagility#132]
This issue can manifest in different scenarios

---

**Scenario 1: benchit is killed by the OS**

**Description:**

When benchmarking multiple models on a single benchit command, a single process is used. If any of the models exceed the maximum amount of memory available, the process will be killed by the OS. As a result, some models might not even be tested.

**Task:** 

* Ensure that each benchit model generates a separate process

--- 

**Scenario 2: `benchit` raises an exception**

**Description:**

`benchit` stops if a single model fails due to assertions/exceptions. 

**To reproduce:**

`benchit models/*/*.py --labels test_group::mlagility --device x86`

**Expected stack trace (fails on UNET 2D):**

```
  File "/home/dhnoronha/miniconda3/envs/ort_env/bin/benchit", line 33, in <module>
    sys.exit(load_entry_point('mlagility', 'console_scripts', 'benchit')())
  File "/home/dhnoronha/mlagility/src/mlagility/cli/cli.py", line 437, in main
    args.func(args)
  File "/home/dhnoronha/mlagility/src/mlagility/cli/cli.py", line 44, in benchmark_script_argparse
    benchmark_script(
  File "/home/dhnoronha/mlagility/src/mlagility/api/script_api.py", line 218, in benchmark_script
    models_found = evaluate_script(tracer_args, script_args)
  File "/home/dhnoronha/mlagility/src/mlagility/analysis/analysis.py", line 500, in evaluate_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dhnoronha/mlagility/models/diffusers/clip_text_encoder.py", line 5, in <module>
    from diffusers import StableDiffusionPipeline
  File "/home/dhnoronha/miniconda3/envs/ort_env/lib/python3.8/site-packages/diffusers/__init__.py", line 27, in <module>
    from .pipelines import OnnxRuntimeModel
  File "/home/dhnoronha/miniconda3/envs/ort_env/lib/python3.8/site-packages/diffusers/pipelines/__init__.py", line 18, in <module>
    from .dance_diffusion import DanceDiffusionPipeline
  File "/home/dhnoronha/miniconda3/envs/ort_env/lib/python3.8/site-packages/diffusers/pipelines/dance_diffusion/__init__.py", line 1, in <module>
    from .pipeline_dance_diffusion import DanceDiffusionPipeline
  File "/home/dhnoronha/miniconda3/envs/ort_env/lib/python3.8/site-packages/diffusers/pipelines/dance_diffusion/pipeline_dance_diffusion.py", line 21, in <module>
    from ..pipeline_utils import AudioPipelineOutput, DiffusionPipeline
  File "/home/dhnoronha/miniconda3/envs/ort_env/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 63, in <module>
    from transformers.utils import SAFE_WEIGHTS_NAME as TRANSFORMERS_SAFE_WEIGHTS_NAME
ImportError: cannot import name 'SAFE_WEIGHTS_NAME' from 'transformers.utils' (/home/dhnoronha/miniconda3/envs/ort_env/lib/python3.8/site-packages/transformers/utils/__init__.py)
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f039abc8c10>
Traceback (most recent call last):
  File "/home/dhnoronha/miniconda3/envs/ort_env/lib/python3.8/weakref.py", line 103, in remove
  File "/home/dhnoronha/mlagility/src/mlagility/analysis/analysis.py", line 425, in tracefunc
  File "/home/dhnoronha/mlagility/src/mlagility/analysis/analysis.py", line 262, in explore_frame
TypeError: 'NoneType' object is not callable
```

Temporary workaround:

On `scripts_api.py`
```
  # Run analysis, build, and benchmarking on every model
  # in the script
  try:
      models_found = evaluate_script(tracer_args, script_args)
  except:
      pass
```

**Comment by danielholanda** [comment]
Similar issue: https://github.com/groq/mlagility/issues/170

A good solution for #132 will likely also solve https://github.com/groq/mlagility/issues/170
