### ISSUE TITLE
`benchit` crashes on parallel execution

### ISSUE THREAD

**Issue by danielholanda** [groq/mlagility#169]
**Issue:**

The logic used to implement the `resume` feature seems to break any sort of parallel execution of benchit **even it the `--resume` flag is not used at all**.

**To reproduce:**

* Get the latest version of benchit
* `rm -rf ~/.cache/mlagility`
* cd into Groq folder (to enable SDK to be baked)
* `benchit <PATH_TO_MLAGILITY>/models/*/*.py --labels test_group::mlagility --device groq --build-only --use-slurm`

**Stack trace of most models:**

```
Traceback (most recent call last):
  File "/net/home/dhnoronha/miniconda3/envs/tracker_slurm/bin/benchit", line 33, in <module>
    sys.exit(load_entry_point('mlagility', 'console_scripts', 'benchit')())
  File "/net/home/dhnoronha/mlagility/src/mlagility/cli/cli.py", line 437, in main
    args.func(args)
  File "/net/home/dhnoronha/mlagility/src/mlagility/cli/cli.py", line 44, in benchmark_script_argparse
    benchmark_script(
  File "/net/home/dhnoronha/mlagility/src/mlagility/api/script_api.py", line 172, in benchmark_script
    if db.exists():
  File "/net/home/dhnoronha/mlagility/src/mlagility/common/filesystem.py", line 78, in exists
    return len(self._database) > 0
  File "/net/home/dhnoronha/mlagility/src/mlagility/common/filesystem.py", line 65, in _database
    return _load_yaml(self._database_file)
  File "/net/home/dhnoronha/mlagility/src/mlagility/common/filesystem.py", line 33, in _load_yaml
    return yaml.load(stream, Loader=yaml.FullLoader)
  File "/net/home/dhnoronha/miniconda3/envs/tracker_slurm/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/net/home/dhnoronha/miniconda3/envs/tracker_slurm/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/net/home/dhnoronha/miniconda3/envs/tracker_slurm/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/net/home/dhnoronha/miniconda3/envs/tracker_slurm/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/net/home/dhnoronha/miniconda3/envs/tracker_slurm/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/net/home/dhnoronha/miniconda3/envs/tracker_slurm/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/net/home/dhnoronha/miniconda3/envs/tracker_slurm/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/net/home/dhnoronha/miniconda3/envs/tracker_slurm/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/net/home/dhnoronha/miniconda3/envs/tracker_slurm/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/net/home/dhnoronha/miniconda3/envs/tracker_slurm/lib/python3.8/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/net/home/dhnoronha/miniconda3/envs/tracker_slurm/lib/python3.8/site-packages/yaml/scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "/net/home/dhnoronha/miniconda3/envs/tracker_slurm/lib/python3.8/site-packages/yaml/scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/net/home/dhnoronha/miniconda3/envs/tracker_slurm/lib/python3.8/site-packages/yaml/scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "/net/home/dhnoronha/cache/.cache_database.yaml", line 102, column 1
could not find expected ':'
  in "/net/home/dhnoronha/cache/.cache_database.yaml", line 103, column 1
```

**Comment by danielholanda** [comment]
@jeremyfowers for vis

**Comment by jeremyfowers** [comment]
Makes sense (sadly). Multiple parallel slurm workers trying to access the same cache_database.yaml would collide. We will need to move to a more robust method for keeping track of builds.

**Comment by jeremyfowers** [comment]
Took a look at `flock` https://pypi.org/project/flock/ as a potential solution. However, `flock` "does not work over NFS", and Slurm is only used over NFS, so that isn't so good.

**Comment by jeremyfowers** [comment]
Another option would be to move the database management code outside of the Slurm domain. For example:
1. benchmark_script(use_slurm=True) is called in the main process
2. input_scripts are added to database in the main process
3. Slurm workers run (spawning parallel sub-processes)
4. builds are added to database in the main process after each slurm worker returns

**Comment by danielholanda** [comment]
> Another option would be to move the database management code outside of the Slurm domain. 

That sounds like an interesting approach, but imagine someone does the following (without even using Slurm):

On one terminal: `benchit folder_a/*.py `
On a second terminal: `benchit folder_b/*.py `

Isn't there a way of keeping track of which models were previously executed while also avoiding collisions? Perhaps by using a single file for all models? Or use [a database library that allows for atomic transactions](https://www.tutorialspoint.com/peewee/peewee_atomic_transactions.htm)?
