### ISSUE TITLE
`benchit` stops if a single model fails

### ISSUE THREAD

**Issue by danielholanda** [groq/mlagility#170]
**Issue:**

`benchit` stops if a single model fails.

**To reproduce:**

`benchit models/*/*.py --labels test_group::mlagility --device x86`

**Expected stack trace (fails on UNET 2D):**

```
  File "/home/dhnoronha/miniconda3/envs/ort_env/bin/benchit", line 33, in <module>
    sys.exit(load_entry_point('mlagility', 'console_scripts', 'benchit')())
  File "/home/dhnoronha/mlagility/src/mlagility/cli/cli.py", line 437, in main
    args.func(args)
  File "/home/dhnoronha/mlagility/src/mlagility/cli/cli.py", line 44, in benchmark_script_argparse
    benchmark_script(
  File "/home/dhnoronha/mlagility/src/mlagility/api/script_api.py", line 218, in benchmark_script
    models_found = evaluate_script(tracer_args, script_args)
  File "/home/dhnoronha/mlagility/src/mlagility/analysis/analysis.py", line 500, in evaluate_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dhnoronha/mlagility/models/diffusers/clip_text_encoder.py", line 5, in <module>
    from diffusers import StableDiffusionPipeline
  File "/home/dhnoronha/miniconda3/envs/ort_env/lib/python3.8/site-packages/diffusers/__init__.py", line 27, in <module>
    from .pipelines import OnnxRuntimeModel
  File "/home/dhnoronha/miniconda3/envs/ort_env/lib/python3.8/site-packages/diffusers/pipelines/__init__.py", line 18, in <module>
    from .dance_diffusion import DanceDiffusionPipeline
  File "/home/dhnoronha/miniconda3/envs/ort_env/lib/python3.8/site-packages/diffusers/pipelines/dance_diffusion/__init__.py", line 1, in <module>
    from .pipeline_dance_diffusion import DanceDiffusionPipeline
  File "/home/dhnoronha/miniconda3/envs/ort_env/lib/python3.8/site-packages/diffusers/pipelines/dance_diffusion/pipeline_dance_diffusion.py", line 21, in <module>
    from ..pipeline_utils import AudioPipelineOutput, DiffusionPipeline
  File "/home/dhnoronha/miniconda3/envs/ort_env/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 63, in <module>
    from transformers.utils import SAFE_WEIGHTS_NAME as TRANSFORMERS_SAFE_WEIGHTS_NAME
ImportError: cannot import name 'SAFE_WEIGHTS_NAME' from 'transformers.utils' (/home/dhnoronha/miniconda3/envs/ort_env/lib/python3.8/site-packages/transformers/utils/__init__.py)
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f039abc8c10>
Traceback (most recent call last):
  File "/home/dhnoronha/miniconda3/envs/ort_env/lib/python3.8/weakref.py", line 103, in remove
  File "/home/dhnoronha/mlagility/src/mlagility/analysis/analysis.py", line 425, in tracefunc
  File "/home/dhnoronha/mlagility/src/mlagility/analysis/analysis.py", line 262, in explore_frame
TypeError: 'NoneType' object is not callable
```

**Comment by danielholanda** [comment]
@jeremyfowers for vis

**Comment by jeremyfowers** [comment]
@danielholanda can you merge this into #132 since they have the same root cause?

**Comment by danielholanda** [comment]
merged this issue into https://github.com/groq/mlagility/issues/132 as requested
