### ISSUE TITLE
Benchmarking docker not stopped if a run fails

### ISSUE THREAD

**Issue by ramkrishna2910** [groq/mlagility#224]
```
mlagility.api.devices.BenchmarkException: Error: Failure to run model using ORT - ERROR:root:Subprocess failed with command: docker run -d --rm -v tmp_cache/sample/x86_benchmark:/app --name mlagility-onnxruntime-mlas-ep mlagility-onnxruntime-image and error message: docker: Error response from daemon: Conflict. The container name "/mlagility-onnxruntime-mlas-ep" is already in use by container "5a5e5eb76a6069b3a8c600d9d597951c8673db404c87b90ba82d51ba1b8a9a7d". You have to remove (or rename) that container to be able to reuse that name.
```
Container needs to be removed in any case so the container name does not conflict with the next run.

**Comment by jeremyfowers** [comment]
I am able to reproduce this problem by raising a ValueError within the container:

```
Traceback (most recent call last):
  File "/net/home/jfowers/miniconda3/envs/mlaof/bin/benchit", line 33, in <module>
    sys.exit(load_entry_point('mlagility', 'console_scripts', 'benchit')())
  File "/home/jfowers/mlagility/src/mlagility/cli/cli.py", line 483, in main
    args.func(args)
  File "/home/jfowers/mlagility/src/mlagility/cli/cli.py", line 94, in benchmark_command
    benchmark_model(
  File "/home/jfowers/mlagility/src/mlagility/api/model_api.py", line 117, in benchmark_model
    perf = cpu_model.benchmark(backend=backend)
  File "/home/jfowers/mlagility/src/mlagility/api/ortmodel.py", line 19, in benchmark
    benchmark_results = self._execute(repetitions=repetitions, backend=backend)
  File "/home/jfowers/mlagility/src/mlagility/api/ortmodel.py", line 74, in _execute
    devices.execute_ort_locally(
  File "/home/jfowers/mlagility/src/mlagility/api/devices.py", line 623, in execute_ort_locally
    raise BenchmarkException(
mlagility.api.devices.BenchmarkException: Error: Failure to run model using ORT - Traceback (most recent call last):
  File "/home/jfowers/mlagility/examples/cli/onnx/tmp_cache/sample/x86_benchmark/setup_ort.py", line 131, in run
    perf_result = execute_benchmark(onnx_file, docker_name, num_iterations)
  File "/home/jfowers/mlagility/examples/cli/onnx/tmp_cache/sample/x86_benchmark/setup_ort.py", line 74, in execute_benchmark
    raise ValueError(f"Execution of command {cmd} failed with stderr: {stderr}")
ValueError: Execution of command docker exec mlagility-onnxruntime-mlas-ep /usr/bin/python3 /app/run_ort_model.py --onnx-file /app/onnxmodel/model.onnx --iterations 100 failed with stderr: b'Traceback (most recent call last):\n  File "/app/run_ort_model.py", line 90, in <module>\n    run_ort_profile(\n  File "/app/run_ort_model.py", line 26, in run_ort_profile\n    onnx_session.run([output_name], input_feed)\n  File "/usr/local/lib/python3.9/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 200, in run\n    return self._sess.run(output_names, input_feed, run_options)\nonnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(double)) , expected: (tensor(float))\n'
```

And then the subsequent run of `benchit` produces the "name collision" error above:

```
Info: Benchmarking on local x86...
Traceback (most recent call last):
  File "/net/home/jfowers/miniconda3/envs/mlaof/bin/benchit", line 33, in <module>
    sys.exit(load_entry_point('mlagility', 'console_scripts', 'benchit')())
  File "/home/jfowers/mlagility/src/mlagility/cli/cli.py", line 483, in main
    args.func(args)
  File "/home/jfowers/mlagility/src/mlagility/cli/cli.py", line 94, in benchmark_command
    benchmark_model(
  File "/home/jfowers/mlagility/src/mlagility/api/model_api.py", line 117, in benchmark_model
    perf = cpu_model.benchmark(backend=backend)
  File "/home/jfowers/mlagility/src/mlagility/api/ortmodel.py", line 19, in benchmark
    benchmark_results = self._execute(repetitions=repetitions, backend=backend)
  File "/home/jfowers/mlagility/src/mlagility/api/ortmodel.py", line 74, in _execute
    devices.execute_ort_locally(
  File "/home/jfowers/mlagility/src/mlagility/api/devices.py", line 623, in execute_ort_locally
    raise BenchmarkException(
mlagility.api.devices.BenchmarkException: Error: Failure to run model using ORT - ERROR:root:Subprocess failed with command: docker run -d --rm -v /home/jfowers/mlagility/examples/cli/onnx/tmp_cache/sample/x86_benchmark:/app --name mlagility-onnxruntime-mlas-ep mlagility-onnxruntime-image and error message: docker: Error response from daemon: Conflict. The container name "/mlagility-onnxruntime-mlas-ep" is already in use by container "f8ddd7f10cb961a538b970988a9ea674b24abeb22403f9e85ef57e9e3718a41a". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
```
