### ISSUE TITLE
Analysis fails: Model hash not found

### ISSUE THREAD

**Issue by danielholanda** [groq/mlagility#322]
## Description

Some models are now failing analysis due to the model hash not being found. This has potentially been caused by [mlagility.analysis using the model's weights to calculate the hash](https://github.com/groq/mlagility/pull/317).

## Reproducing

Command to reproduce:

```
benchit models/timm/mobilenetv2_035.py --analyze-only
```

Expected error:

```
Traceback (most recent call last):
  File "/net/home/dhnoronha/miniconda3/envs/dse_slurm/bin/benchit", line 8, in <module>
    sys.exit(benchitcli())
  File "/net/home/dhnoronha/mlagility/src/mlagility/cli/cli.py", line 571, in main
    args.func(args)
  File "/net/home/dhnoronha/mlagility/src/mlagility/cli/cli.py", line 47, in benchmark_command
    benchmark_files(
  File "/net/home/dhnoronha/mlagility/src/mlagility/api/script_api.py", line 330, in benchmark_files
    benchmark_script(
  File "/net/home/dhnoronha/mlagility/src/mlagility/api/script_api.py", line 272, in benchmark_script
    models_found = evaluate_script(tracer_args, script_args)
  File "/net/home/dhnoronha/mlagility/src/mlagility/analysis/analysis.py", line 567, in evaluate_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/net/home/dhnoronha/mlagility/models/timm/mobilenetv2_035.py", line 19, in <module>
    model(inputs)
  File "/net/home/dhnoronha/miniconda3/envs/dse_slurm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/net/home/dhnoronha/mlagility/src/mlagility/analysis/analysis.py", line 442, in forward_spy
    model_info = tracer_args.models_found[model_hash]
KeyError: '9110a638'
```

**Comment by danielholanda** [comment]
@jeremyfowers @ramkrishna2910

**Comment by jeremyfowers** [comment]
Proposed solution:
1. implement the long-term solution and revert the workaround mentioned here: https://github.com/groq/mlagility/issues/316#issuecomment-1581373641 (closing #316 in the same PR)
2. Add a test to test/analysis.py to prevent this kind of break in the future (perhaps as simple as running `benchit models/timm/mobilenetv2_035.py --analyze-only` and maybe 1 or two more tiny models from `timm`?)
