### ISSUE TITLE
`benchit benchmark` throws an error

### ISSUE THREAD

**Issue by jeremyfowers** [groq/mlagility#66]
If you call `benchit benchmark` with no additional args you can get an error like:
```
(mla) jfowers@jfowers:~/mlagility$ benchit benchmark
2023-02-06 07:50:10.187723: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/net/home/jfowers/miniconda3/envs/mla/bin/benchit", line 33, in <module>
    sys.exit(load_entry_point('mlagility', 'console_scripts', 'benchit')())
  File "/home/jfowers/mlagility/src/mlagility/cli/cli.py", line 420, in main
    args.func(args)
  File "/home/jfowers/mlagility/src/mlagility/cli/benchmark.py", line 137, in main
    evaluate_script(tracer_args, args.script_args)
  File "/home/jfowers/mlagility/src/mlagility/analysis/analysis.py", line 421, in evaluate_script
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 553, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'
```

I believe what is happening here is that benchit is trying to analyze all scripts in the command line dir, which can produce some funky results.

A few different ways to think about this bug:
- Should `benchit benchmark` should require some arg(s) to guide users towards proper usage?
- Should `benchit benchmark` take a single input script, instead of a `--input-scripts` with `nargs="+"`? That would let us force users to supply a positional argument. 
  - We could make it work just like the `benchit cache delete` command: you either supply a positional arg, or the `--all` arg. I like this solution! I don't think people will supply multiple input scripts by name very often.
- ALSO, `analysis` should catch the error above and give a better exception message than `AttributeError: 'NoneType' object has no attribute 'loader'`

**Comment by jeremyfowers** [comment]
cc @danielholanda
