### ISSUE TITLE
Throw a helpful error message when remote benchmarking fails

### ISSUE THREAD

**Issue by jeremyfowers** [groq/mlagility#80]
Current behavior is to get an exception like this:

```
Traceback (most recent call last):
  File "/net/home/jfowers/miniconda3/envs/mla/bin/benchit", line 33, in <module>
    sys.exit(load_entry_point('mlagility', 'console_scripts', 'benchit')())
  File "/home/jfowers/mlagility/src/mlagility/cli/cli.py", line 406, in main
    args.func(args)
  File "/home/jfowers/mlagility/src/mlagility/cli/benchmark.py", line 148, in main
    with open(perf_file, "r", encoding="utf8") as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jfowers/.cache/mlagility/hello_world_479b1332/cpu_performance.json'
```

This exception is a fairly common occurrence. Can we catch it and say something more helpful?

**Comment by jeremyfowers** [comment]
cc @ramkrishna2910 @danielholanda

**Comment by jeremyfowers** [comment]
Moving out of the first release, since remote benchmarking is not part of the first release.
