### ISSUE TITLE
pip install of local mlagility clone only works in -e mode

### ISSUE THREAD

**Issue by jeremyfowers** [groq/mlagility#90]
The command:

```
~/mlagility$ pip install .
```

yields:

```
>>> import mlagility
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jfowers/miniconda3/envs/mla/lib/python3.8/site-packages/mlagility/__init__.py", line 3, in <module>
    from .api.api import benchit
ModuleNotFoundError: No module named 'mlagility.api'
```

However, this command works:

```
~/mlagility$ pip install -e .
```

Seems bad!

**Comment by jeremyfowers** [comment]
cc @danielholanda @ramkrishna2910 for fyi. Seems low-prio because there's an easy workaround.
